### ISSUE TITLE
CocoaPod dependency problem

### ISSUE THREAD

**Issue by andresousaribeiro** [jamesdouble/JDSwiftHeatMap#2]
I'm trying to use the Pod for this library but i constantly get this error:

pod install
Analyzing dependencies
[!] Unable to find a specification for `JDSWiftHeatMap`

How can i resolve this?

**Comment by andresousaribeiro** [comment]
http://cocoadocs.org/docsets/JDSwiftHeatMap/1.0.0/#
On the website of cocoa docs is getting also a error:
"Error Parsing Pod

Could not find Objective-C Classes."

**Comment by jamesdouble** [comment]
Which language do you use in your project?
Swift or OC?

**Comment by andresousaribeiro** [comment]
I'm using Swift.

**Comment by jamesdouble** [comment]
Don't know why Cocoapods have error parse my pod last time.
Now, work fine.
Thanks for feedback

**Comment by cleveralmeida** [comment]
Hi James !

I have tried to install pod but I am getting: Unable to find a specification for `JDSWiftHeatMap`.
My code is in swift 3.2 and target is ios 9.

**Comment by jamesdouble** [comment]
@cleveralmeida 
I reinstalled 'JDSWiftHeatMap' in pod , and its works fine.
Maybe use  pod update?

**Comment by cleveralmeida** [comment]
Hi @jamesdouble, 

    Thank you for your replay. I just updated pod and try again but same result. I use other pod libraries and it is working fine just this shows me "[!] Unable to find a specification for `JDSWiftHeatMap`"

**Comment by jamesdouble** [comment]
@cleveralmeida 
I can't find the reason.
Library on cocoapod seems worked.
Here is my podfile

```
platform :ios,'10.0'

workspace 'Test'

project 'TestMyPod'

 target :TestMyPod do  
 project 'TestMyPod'
 pod 'JDSwiftHeatMap'
 use_frameworks!
 end
```

**Comment by panychyk** [comment]
cannot inject pod into project. will include as files
