### ISSUE TITLE
fatal error: RenderPair may be wrong in xcode 9

### ISSUE THREAD

**Issue by rohaaa** [jamesdouble/JDSwiftHeatMap#3]
As the title indicates an error appears when I run the demo on the simulator. How to solve it? Another question: Is an update to swift 4 scheduled?

**Comment by jamesdouble** [comment]
Hi @rohaaa , thanks for reply.
If there are some screenshots would help me debug.
I  stuck with updating new version around Swift4 and IOS11,
because there appear some bug in IOS11 Apple native map ( Overlay , Render).

**Comment by rohaaa** [comment]
Hi @jamesdouble, you're right, that's what causes the crush 
<img width="1382" alt="capture d ecran 2017-10-19 a 23 14 15" src="https://user-images.githubusercontent.com/32855874/31794793-c88b9478-b523-11e7-9119-f387918ca388.png">

**Comment by yuvarajagna** [comment]
Any update regarding this issue.

**Comment by rohaaa** [comment]
@yuvarajagna Hi, to make it work you can try to remove/comment fatalError("RenderPair may be wrong") or put it under "else" condition of "if let render = renderFor(overlay: heatoverlay)". The current version isn't stable enough.

**Comment by jamesdouble** [comment]
Sorry for keeping open this issue so long,
previously , I am looking for a job. 
So I didn't have enough time coding.
I will start debugging recently.

**Comment by jamesdouble** [comment]
![2017-12-06 11 23 18](https://user-images.githubusercontent.com/9458771/33669126-8de5f9d8-dadc-11e7-8e56-e3de3519087c.png)

this function return nil cause the problem

**Comment by jamesdouble** [comment]
OK, I found it 
reference:
https://stackoverflow.com/questions/18906981/mkmapview-rendererforoverlay-not-called
